<?php
/** @var Controller $this */
use App\App;
use Core\Controllers\Controller; ?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=0.8, minimum-scale=0.8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="Vince">
    <meta property="og:type" content="website">
    <meta http-equiv="content-language" content="fr">
    <!-- Ios meta -->
    <meta name="apple-mobile-web-app-title" content="Blog PHP">
    <!-- Ios meta end -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" >
    <link rel="shortcut icon" href="<?= App::getHost() ?>/public/assets/img/logo.png" type="image/x-icon">
    <?php // Get additional stylesheets ?>
    <?php foreach ($this->getStylesheetsPaths() as $stylesheetPath): ?>
        <link rel="stylesheet" href="<?= App::getHost() . '/public' . $stylesheetPath . '?v=' . App::getConfig('css_version') ?>">
    <?php endforeach; ?>
    <title><?= mb_strtoupper($this->meta->getTitle()) ?></title>
</head>
<body class="min-vh-100">