</body>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/9011deb8a1.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<?php use App\App;
foreach ($this->getScripts() as $script): ?>
    <script type="<?= $script['type'] ?>"
            src="<?=  App::getHost() . '/public' . $script['path'] . '?v=' .  App::getConfig('js_version') ?>">
    </script>
<?php endforeach; ?>
<script>
    const HOST_URL = "<?= App::getHost() ?>";

    /**
     * Success alert
     *
     * @param msg
     * @param redirect
     * @param reload
     */
    function success(msg, redirect = null, reload = false) {
        if (confirm(msg)) {
            if (redirect) {
                window.location.href = HOST_URL + redirect;
            } else if (reload) {
                window.location.reload();
            }
        }
    }

</script>
