<?php
namespace App\Controllers;

use App\App;
use Core\Controllers\Controller;

/**
 * Class IndexController
 * @package App\Controllers
 */
class IndexController extends Controller
{

    public function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub
    }

}