<?php
namespace App\Controllers;

use Core\Controllers\Controller;

/**
 *
 */
class LoginController extends Controller
{

    public function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub
    }

}