<?php

use App\App;

?>
<section class="d-flex align-items-center justify-content-center my-5" style="min-height: 80vh;">
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
                <div class="card text-black border-0">
                    <div class="card-body p-md-5">
                        <div class="row justify-content-center">
                            <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Inscription</p>
                                <form class="mx-1 mx-md-4">
                                    <div class="d-flex flex-row align-items-center mb-4">
                                        <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                                        <div class="form-outline flex-fill mb-0">
                                            <label class="form-label" for="username">Prénom</label>
                                            <input type="text" id="username" class="form-control" required/>
                                        </div>
                                    </div>
                                    <div class="d-flex flex-row align-items-center mb-4">
                                        <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                                        <div class="form-outline flex-fill mb-0">
                                            <label class="form-label" for="username">Nom</label>
                                            <input type="text" id="username" class="form-control" required/>
                                        </div>
                                    </div>
                                    <div class="d-flex flex-row align-items-center mb-4">
                                        <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                                        <div class="form-outline flex-fill mb-0">
                                            <label class="form-label" for="username">Nom d'utilisateur</label>
                                            <input type="text" id="username" class="form-control" required/>
                                        </div>
                                    </div>
                                    <div class="d-flex flex-row align-items-center mb-4">
                                        <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                                        <div class="form-outline flex-fill mb-0">
                                            <label class="form-label" for="email">Votre adresse mail</label>
                                            <input type="email" id="email" class="form-control" required/>
                                            <small class="form-text text-muted">Utilisé une adresse mail qui n'est pas déjà associer à un compte</small>
                                        </div>
                                    </div>
                                    <div class="d-flex flex-row align-items-center mb-4">
                                        <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                                        <div class="form-outline flex-fill mb-0">
                                            <label class="form-label" for="password">Mot de passe</label>
                                            <input type="password" id="password" class="form-control" required/>
                                            <small class="form-text text-muted">Votre mot de passe dois faire plus de 4 caratères</small>
                                        </div>
                                    </div>
                                    <div class="d-flex flex-row align-items-center mb-4">
                                        <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                                        <div class="form-outline flex-fill mb-0">
                                            <label class="form-label" for="comfirm-password">Comfirmez votre mot de passse</label>
                                            <input type="password" id="comfirm-password" class="form-control" required/>
                                            <small class="form-text text-muted">Répétez votre mot de passe</small>
                                        </div>
                                    </div>
                                    <div class="form-check d-flex justify-content-center mb-5">
                                        <input
                                            class="form-check-input me-2"
                                            type="checkbox"
                                            value=""
                                            id="terms"
                                        />
                                        <label class="form-check-label" for="terms">
                                            J'accepte les <a href="<?= App::getHost() ?>/tos">conditions d'utilisations</a>
                                        </label>
                                    </div>
                                    <input type="text" id="form-token" value="<?= App::registry('token_register') ?>" style="display: none;"/>
                                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                        <button id="register-button" type="button" class="btn btn-primary btn-lg">S'inscrire</button>
                                    </div>
                                    <p class="text-center small text-muted">Vous avez déjà un compte ? <a href="<?= App::getHost() ?>/login">Connectez-vous</a> maintenant.</p>
                                </form>
                            </div>
                            <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
                                <img src="https://mdbootstrap.com/img/Photos/new-templates/bootstrap-registration/draw1.png"
                                     class="img-fluid" alt="Sample image">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>